### ISSUE TITLE
Add Better Terminal Log Support

### ISSUE THREAD

**Issue by tac01337** [tzfun/vue-web-terminal#129]
**Feature or optimization description**
I need to be able to store the history of the terminalLog into a backend db to keep track of a users history of commands.

I also need the history to be more accessible. I couldn't find a way to access messages via an index? I need to be able to update/append messages[i] not just the last message like in appendMessage()

**Applicable scene**
Be able to have multiple commands be fired off into a backend queue and update the message later on when they are finished processing.

**Comment by tzfun** [comment]
All logs are caller triggered (using callback or pushMessage API), which means you have control over the logs, and can also store the logs in the backend before or after displaying them to the terminal.


Regarding the second point, I'm sorry that I can't implement it because your requirements don't match the design of this project. The log in the window is a display and archive. Only the last log can be edited (dynamic update). The rest of the historical logs can be considered archived and can no longer be modified. Just like the console in the program, you can only modify the last log and cannot modify the displayed log.
